[build-system]
requires = [
    "Cython>=0.29.6",
    "pkgconfig>=1.4.0",
    "setuptools>=40.6.0",
    "wheel",  # Needed for versions of pip not implementing PEP-517
]

build-backend = 'setuptools.build_meta'

[tool.pytest.ini_options]
xfail_strict=true
